name: GitHub Actions Cloudflare Pages Deployment
on:
    push:
        branches: [main]
        
permissions:
  contents: read
  deployments: write
      
jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: yarn install && yarn build
        
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: cloudflaretest
          directory: build
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

